### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by nalogowiec** [warchimede/RangeSlider#21]
Hey, great work with the slider! I used it without any problems with Swift 2.2, but then I migrated to Swift 3 and now I have some small problems, it does not compile because of those lines:

 override func layoutSublayersOfLayer(_ layer: CALayer) {
        super.layoutSublayersOfLayer(layer)
        updateLayerFrames()
    }

the error states this function does not override anything in the superclass...

**Comment by Sundin** [comment]
Try changing it to:

override func layoutSublayers(of layer: CALayer) {
super.layoutSublayers(of: layer)
updateLayerFrames()
}

The reason is that this function has been renamed in Swift 3.

**Comment by nalogowiec** [comment]
Thank you man for a quick solution and a great answer, it of course works :)
