### ISSUE TITLE
Unable to find a specification for WARangeSlider

### ISSUE THREAD

**Issue by dougdss** [warchimede/RangeSlider#24]
Hello, I think there's a problem with the pod.
the error: Unable to find a specification for `WARangeSlider` appears when I try to install.

**Comment by warchimede** [comment]
Hi @dougdss,
Have you tried `pod repo update` before doing `pod install` ?

**Comment by dougdss** [comment]
thanks @warchimede,
after updating the `pod repo` it works fine.
