### ISSUE TITLE
doesn't load size and range values unless you touch the knobs

### ISSUE THREAD

**Issue by gadget00** [warchimede/RangeSlider#6]
when I run my app, the slider doesn't pick the constraints assigned to it and looks totally out of place, unless I touch one of the knobs and make the gesture of moving them.  When I do that touch in the knob, the constraints load and the sizing gets corrected.  Am I doing something wrong or is that some problem related to the rangeslider itself??

**Comment by sgwilly** [comment]
Thanks for using RangeSlider !
I don't reproduce the issue, are you using it in a storyboard ? How do you add the constraints ?
If you do it in your code, do you call setNeedsLayout() after adding them ?

**Comment by senseluo** [comment]
hi @warchimede 
here I reproduced what @gadget00 experienced.

I am using  Xcode 7.2.1 storyboard the range slider doesn't fit its uiview's constraint  unless you manually touch the knob.

Please check the screenshots.  
Thanks!

![screen shot 2016-03-01 at 3 51 01 pm](https://cloud.githubusercontent.com/assets/128367/13420944/7c91f948-dfc5-11e5-9544-f0111a79bb85.png)
![screen shot 2016-03-01 at 3 51 15 pm](https://cloud.githubusercontent.com/assets/128367/13420943/7c914c64-dfc5-11e5-8f84-1ec41521e2e3.png)

**Comment by warchimede** [comment]
Hi @gadget00, @senseluo,
I may have fixed this issue in commit https://github.com/warchimede/RangeSlider/commit/937106d989ac15e141ed530325936c4b3a8eb769
If you could take a look and let me know if your problem is really solved, that would be great.
Thanks ! :100:
